language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
after_success:
  - make docker_push
deploy:
  provider: heroku
  app: aqueous-reef-29112
  api_key: ${HEROKU_API_KEY}
